FROM nvidia/cuda:12.5.1-runtime-ubuntu24.04

RUN mkdir -p /opt/pkg
WORKDIR /opt/

COPY requirements.txt /opt/pkg/requirements.txt

COPY kneel /opt/pkg/kneel
COPY setup.py /opt/pkg/setup.py
RUN touch /opt/pkg/README.md
RUN apt-get update -q && \
    apt-get install -q -y --no-install-recommends \
        python3-full \
        python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* && ln -s /usr/bin/python3 /usr/bin/python
RUN python3 -m pip install --no-cache-dir --break-system-packages -e /opt/pkg